### ISSUE TITLE
System.Drawing.Common is not supported on non-Windows platforms. 

### ISSUE THREAD

**Issue by Myeeoo** [opentk/LearnOpenTK#77]
Big sur 11.2.2
OpenTK 4.7.4
libgdiplus
5-Textures
System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information.
I uninstalled libgdiplus and nuget sixlabs Imagesharp, but the problem exists？

**Comment by utkumaden** [comment]
Help us help you. You have not provided much information for us. The tutorials were written for .net framework which guaranteed system.drawing. Then the code samples were later ported to .net core where for a long time it was available on all platforms with the system.drawing.common package.

You say you have replaced system.drawing with sixlabors.imagesharp but have you modified the code at all? If so what kind of error do you get? We would love to be able to tell what happened from our screens but it is not very possible without seeing any exception trace or a compiler error.

Finally we usually take questions like this on our discord server at [https://discord.gg/6HqD48s](https://discord.gg/6HqD48s). Feel free to updates us either there or give us more information about your issue here.

**Comment by NogginBops** [comment]
I have just updated the tutorial to no longer use `System.Drawing.Common`, so this should not be a problem any more.
Closing this, but if you feel the problem has not  been solved, feel free to open this issue again 🙂
